before_script: [export GRADLE_USER_HOME=`pwd`/.gradle]

cache:
  paths: [.gradle/caches]

test-server:
  image: openjdk:8
  script: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.test.yml --project-directory .
    run --rm prototype
  artifacts:
    when: always
    paths: [build/reports/tests/test/]