version: '3.7'
services:
  prototype:
    image: gradle:6.2.1-jdk8
    # The directory must be named "backend-prototype" because automatic reload watches a directory by that name.
    # The directory must be nested (i.e., "/backend-prototype" will not work).
    working_dir: /home/gradle/backend-prototype
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /home/gradle/backend-prototype
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
      - type: volume
        source: cache
        target: /home/gradle/.gradle
volumes:
  cache: